![rmotr](https://user-images.githubusercontent.com/7065401/52071918-bda15380-2562-11e9-828c-7f95297e4a82.png)
<hr style="margin-bottom: 40px;">

<img src="https://user-images.githubusercontent.com/7065401/39118381-910eb0c2-46e9-11e8-81f1-a5b897401c23.jpeg"
    style="width:300px; float: right; margin: 0 40px 40px 40px;"></img>

# Numpy: Numeric computing library

NumPy (Numerical Python) is one of the core packages for numerical computing in Python. Pandas, Matplotlib, Statmodels and many other Scientific libraries rely on NumPy.

NumPy major contributions are:

* Efficient numeric computation with C primitives
* Efficient collections with vectorized operations
* An integrated and natural Linear Algebra API
* A C API for connecting NumPy with libraries written in C, C++, or FORTRAN.

Let's develop on efficiency. In Python, **everything is an object**, which means that even simple ints are also objects, with all the required machinery to make object work. We call them "Boxed Ints". In contrast, NumPy uses primitive numeric types (floats, ints) which makes storing and computation efficient.

<img src="https://docs.google.com/drawings/d/e/2PACX-1vTkDtKYMUVdpfVb3TTpr_8rrVtpal2dOknUUEOu85wJ1RitzHHf5nsJqz1O0SnTt8BwgJjxXMYXyIqs/pub?w=726&h=396" />


![purple-divider](https://user-images.githubusercontent.com/7065401/52071927-c1cd7100-2562-11e9-908a-dde91ba14e59.png)

## Hands on! 

In [1]:
import sys
import numpy as np

## Basic Numpy Arrays

In [2]:
np.array([1, 2, 3, 4])

array([1, 2, 3, 4])

In [3]:
a = np.array([1, 2, 3, 4])

In [4]:
b = np.array([0, .5, 1, 1.5, 2])

In [8]:
a[0], a[1]

(1, 2)

In [7]:
a[0:]

array([1, 2, 3, 4])

In [6]:
a[1:3]

array([2, 3])

In [8]:
a[1:-1]

array([2, 3])

In [9]:
a[::2]

array([1, 3])

In [10]:
b

array([0. , 0.5, 1. , 1.5, 2. ])

In [11]:
b[0], b[2], b[-1]

(0.0, 1.0, 2.0)

In [12]:
b[[0, 2, -1]]

array([0., 1., 2.])

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

## Array Types

In [9]:
a

array([1, 2, 3, 4])

In [10]:
a.dtype

dtype('int32')

In [11]:
b

array([0. , 0.5, 1. , 1.5, 2. ])

In [12]:
b.dtype

dtype('float64')

In [16]:
someArr = np.array([1, 2, 3, 4], dtype=np.int8)

In [18]:
np.array([1, 2, 3, 4], dtype=np.int8)

array([1, 2, 3, 4], dtype=int8)

In [19]:
c = np.array(['a', 'b', 'c'])

In [20]:
c.dtype

dtype('<U1')

In [41]:
d = np.array([{'a': 1}, sys])

In [55]:
print(d)
d[0] = 'asdasd'
print(d.shape)

['asdasd' <module 'sys' (built-in)>]
(2,)


![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

## Dimensions and shapes

In [59]:
A = np.array([
    [1, 2, 3],
    [4, 5, 6]
])

In [60]:
A.shape

(2, 3)

In [61]:
A.ndim

2

In [62]:
A.size

6

In [63]:
B = np.array([
    [
        [12, 11, 10],
        [9, 8, 7],
    ],
    [
        [6, 5, 4],
        [3, 2, 1]
    ]
])

In [64]:
B

array([[[12, 11, 10],
        [ 9,  8,  7]],

       [[ 6,  5,  4],
        [ 3,  2,  1]]])

In [65]:
B.shape

(2, 2, 3)

In [66]:
B.ndim

3

In [67]:
B.size

12

If the shape isn't consistent, it'll just fall back to regular Python objects:

In [69]:
C = np.array([
    [
        [12, 11, 10],
        [9, 8, 7],
        [6, 5, 4]
    ]
])

In [70]:
C.dtype

dtype('int32')

In [71]:
C.shape

(1, 3, 3)

In [72]:
C.size

9

In [75]:
type(C[0] [0])

numpy.ndarray

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

## Indexing and Slicing of Matrices

In [76]:
# Square matrix
A = np.array([
#.   0. 1. 2
    [1, 2, 3], # 0
    [4, 5, 6], # 1
    [7, 8, 9]  # 2
])

In [77]:
A[1]

array([4, 5, 6])

In [80]:
type(A[1][0])
A[1] = 34231

In [ ]:
# A[d1, d2, d3, d4]

In [82]:
A.shape

(3, 3)

In [40]:
A[0:2]

array([[1, 2, 3],
       [4, 5, 6]])

In [41]:
A[:, :2]

array([[1, 2],
       [4, 5],
       [7, 8]])

In [42]:
A[:2, :2]

array([[1, 2],
       [4, 5]])

In [43]:
A[:2, 2:]

array([[3],
       [6]])

In [44]:
A

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [45]:
A[1] = np.array([10, 10, 10])

In [46]:
A

array([[ 1,  2,  3],
       [10, 10, 10],
       [ 7,  8,  9]])

In [47]:
A[2] = 99

In [48]:
A

array([[ 1,  2,  3],
       [10, 10, 10],
       [99, 99, 99]])

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

## Summary statistics

In [49]:
a = np.array([1, 2, 3, 4])

In [50]:
a.sum()

10

In [51]:
a.mean()

2.5

In [52]:
a.std()

1.118033988749895

In [53]:
a.var()

1.25

In [54]:
A = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])

In [55]:
A.sum()

45

In [56]:
A.mean()

5.0

In [57]:
A.std()

2.581988897471611

In [58]:
A.sum(axis=0)

array([12, 15, 18])

In [59]:
A.sum(axis=1)

array([ 6, 15, 24])

In [60]:
A.mean(axis=0)

array([4., 5., 6.])

In [61]:
A.mean(axis=1)

array([2., 5., 8.])

In [62]:
A.std(axis=0)

array([2.44948974, 2.44948974, 2.44948974])

In [63]:
A.std(axis=1)

array([0.81649658, 0.81649658, 0.81649658])

And [many more](https://docs.scipy.org/doc/numpy-1.13.0/reference/arrays.ndarray.html#array-methods)...

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

## Broadcasting and Vectorized operations

In [83]:
a = np.arange(9)

In [84]:
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [86]:
a + 10

array([10, 11, 12, 13, 14, 15, 16, 17, 18])

In [87]:
a * 10

array([ 0, 10, 20, 30, 40, 50, 60, 70, 80])

In [70]:
a

array([0, 1, 2, 3])

In [88]:
a += 100

In [89]:
a

array([100, 101, 102, 103, 104, 105, 106, 107, 108])

In [90]:
l = [0, 1, 2, 3]

In [91]:
[i * 10 for i in l]

[0, 10, 20, 30]

In [94]:
a = np.arange(4)

In [95]:
a

array([0, 1, 2, 3])

In [102]:
b = np.arange(4)

In [103]:
b

array([0, 1, 2, 3])

In [104]:
a + b

array([0, 2, 4, 6])

In [105]:
a * b

array([0, 1, 4, 9])

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

## Boolean arrays
_(Also called masks)_

In [106]:
a = np.arange(4)

In [107]:
a

array([0, 1, 2, 3])

In [108]:
a[0], a[-1]

(0, 3)

In [110]:
a[[0, -1]]

array([0, 3])

In [114]:
a[[True, False, False, True]]

array([0, 3])

In [130]:
a = a + 1

In [133]:
a

array([1, 2, 3, 4])

In [142]:
a[a > 3]

array([4])

In [143]:
a.mean()

2.5

In [145]:
a[a > a.mean()]

array([3, 4])

In [154]:
a[~(a > a.mean())]


array([1, 2])

In [152]:
a[(a == 0) | (a == 1)]

array([1])

In [153]:
a[(a <= 2) & (a % 2 == 0)]

array([2])

In [150]:
A = np.random.randint(100, size=(3, 3))

In [151]:
A

array([[75,  6, 66],
       [30, 67,  7],
       [91, 16, 30]])

In [155]:
A[np.array([
    [True, False, True],
    [False, True, False],
    [True, False, True]
])]

array([75, 66, 67, 91, 30])

In [156]:
A > 30

array([[ True, False,  True],
       [False,  True, False],
       [ True, False, False]])

In [158]:
A[A > 30]

array([75, 66, 67, 91])

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

## Linear Algebra

In [159]:
A = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])

In [160]:
B = np.array([
    [6, 5],
    [4, 3],
    [2, 1]
])

In [161]:
A.dot(B)

array([[20, 14],
       [56, 41],
       [92, 68]])

In [162]:
A @ B

array([[20, 14],
       [56, 41],
       [92, 68]])

In [166]:
B.T

array([[6, 4, 2],
       [5, 3, 1]])

In [167]:
A

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [168]:
B.T @ A

array([[36, 48, 60],
       [24, 33, 42]])

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

## Size of objects in Memory

### Int, floats

In [169]:
# An integer in Python is > 24bytes
sys.getsizeof(1)

28

In [170]:
# Longs are even larger
sys.getsizeof(10**100)

72

In [171]:
# Numpy size is much smaller
np.dtype(int).itemsize

4

In [172]:
# Numpy size is much smaller
np.dtype(np.int8).itemsize

1

In [173]:
np.dtype(float).itemsize

8

### Lists are even larger

In [174]:
# A one-element list
sys.getsizeof([1])

64

In [175]:
# An array of one element in numpy
np.array([1]).nbytes

4

### And performance is also important

In [184]:
l = list(range(12300000))

In [181]:
a = np.arange(12300000)

In [185]:
%time np.sum(a ** 2)

CPU times: total: 31.2 ms
Wall time: 20 ms


-250927664

In [186]:
%time sum([x ** 2 for x in l])

CPU times: total: 1.11 s
Wall time: 1.18 s


620288924355002050000

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

## Useful Numpy functions

### `random` 

In [187]:
np.random.random(size=2)

array([0.16819561, 0.36638645])

In [188]:
np.random.normal(size=2)

array([ 0.14835249, -1.39815639])

In [189]:
np.random.rand(2, 4)

array([[0.93295825, 0.94645497, 0.65278971, 0.79317197],
       [0.85727388, 0.33449841, 0.20655616, 0.32610085]])

---
### `arange`

In [190]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [191]:
np.arange(5, 10)

array([5, 6, 7, 8, 9])

In [193]:
np.arange(0, 1, .2)

array([0. , 0.2, 0.4, 0.6, 0.8])

---
### `reshape`

In [194]:
np.arange(10).reshape(2, 5)

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [195]:
np.arange(10).reshape(5, 2)

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

---
### `linspace`

In [ ]:
np.linspace(0, 1, 5)

In [ ]:
np.linspace(0, 1, 20)

In [ ]:
np.linspace(0, 1, 20, False)

---
### `zeros`, `ones`, `empty`

In [196]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [197]:
np.zeros((3, 3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [ ]:
np.zeros((3, 3), dtype=np.int)

In [198]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [200]:
np.ones((3, 3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [199]:
np.empty(5)

array([1.14074085e-311, 1.14074085e-311, 1.14074085e-311, 1.14074085e-311,
       1.14074085e-311])

In [ ]:
np.empty((2, 2))

---
### `identity` and `eye`

In [ ]:
np.identity(3)

In [203]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [201]:
np.eye(8, 4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [207]:
np.eye(8, 4, k=1)

array([[0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [206]:
np.eye(8, 4, k=-3)

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.],
       [0., 0., 0., 0.]])

In [210]:
"Hello World"[1]

'e'

![purple-divider](https://user-images.githubusercontent.com/7065401/52071927-c1cd7100-2562-11e9-908a-dde91ba14e59.png)